### ISSUE TITLE
17장 2번문제는 22장에 더 적합한 문제 아닐까요!?

### ISSUE THREAD

**Issue by San-Goon** [DuD-Study/DeepDive_Study#6]
17장에 짤막하게 소개된건 맞지만 22장까지가 저희 공부하기로 한 범위니 그쪽에 편입시키는것이 어떤가합니다!

**Comment by zooyaho** [comment]
this와 관련된 문제이니 22장에 추가하도록 하겠습니다~!

**Comment by zooyaho** [comment]
문제 ch.22로 추가했습니다. 확인 부탁드립니다!
